### ISSUE TITLE
[Feature Request]: Stats for client tcp connections

### ISSUE THREAD

**Issue by huyle10** [marcinbudny/eventstore_exporter#29]
Would it be possible to export client TCP connections' statistics individually as shown in web UI?

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/16823972/208956705-3c5780d7-b66a-4bba-b201-9bab7cd303f2.png">

Thanks

**Comment by marcinbudny** [comment]
Hey Huy,

This is possible, connection statistics are returned from `/stats/tcp` API. This needs to be an opt-in feature, similar to streams collection or parked message stats. There could be large numbers of connections, affecting metrics collection and storage in Prometheus.

Let me know if you would like to contribute a PR. Otherwise, I might take a stab at this in the near(ish) future.

**Comment by huyle10** [comment]
Hi Marcin,
I only begin to learn Go or my first compiled language. Let's me read around the repo regarding streams collection first.

**Comment by marcinbudny** [comment]
Hi,
Metrics added in v0.15.0
