### ISSUE TITLE
Context deadline exceeded not store any values

### ISSUE THREAD

**Issue by henri9813** [marcinbudny/eventstore_exporter#40]
Hello,

The exporter doesn't detect all eventstore down:
```
time="2024-05-15T13:39:40Z" level=info msg="Running scrape"
time="2024-05-15T13:39:50Z" level=error msg="Error while getting data from EventStore" error="Get \"http://eventstore.svc.cluster.local:2113/subscriptions\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2024-05-15T13:39:55Z" level=info msg="Running scrape"
```

In the following case I have in my prometheus:
<img width="505" alt="image" src="https://github.com/marcinbudny/eventstore_exporter/assets/4645967/a81af8c9-ee70-4c97-a520-69bf1137a1c8">

This is a problem because no alert is fire ( I configure an alert if up == 0 )

Best regards

**Comment by marcinbudny** [comment]
Hi Henri,

I tested two scenarios:
1. Server was not available which results in `error while getting cluster stats: Get \"http://localhost:2113/gossip\": dial tcp [::1]:2113: connect: connection refused`
2. Server accepts a connection from the exporter but does not send any data, which results in timeout: `error while getting subscription stats: Get \"http://localhost:12345/subscriptions\": context deadline exceeded`

In both cases the exporter correctly reported `eventstore_up 0`.

I think the problem you observed may be related to the timeout configuration. Both Prometheus and the exporter have 10s default scrape timeout. You should adjust these timeouts so that Prometheus one is longer and the information about timed out ES connection can propagate to Prometheus.

You can also consider alerting on the absence of the metric e.g. `absent(eventstore_up) OR eventstore_up == 0` or on the status of the Prometheus job.

**Comment by henri9813** [comment]
Hello,

You right about the prometheus timeout, I forgot this.

However, having the exporter's timeout equal to prometheus one may not be a good idea ? maybe can we consider to reduce it a 5s ( which is already a huge timeout ? )

Thanks for the `absent` keyword.

**Comment by marcinbudny** [comment]
Hi,

Sure, I will consider changing the default timeout on the exporter. It is a bit unfortunate that it matches the Prometheus default timeout. Note, you can configure the exporter's timeout using the `TIMEOUT` env var.

**Comment by henri9813** [comment]
Thank ! can I do a PR for this ?
